# Struktur folder: .streamlit/secrets.toml
[connections.gsheets]
type = "service_account"
project_id = "id-proyek-anda"
private_key_id = "id-private-key-anda"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC...\n-----END PRIVATE KEY-----\n"
client_email = "nama-akun@://gserviceaccount.com"
client_id = "123456789"
auth_uri = "https://google.com"
token_uri = "https://googleapis.com"
auth_provider_x509_cert_url = "https://googleapis.com"
client_x509_cert_url = "https://googleapis.com..."
